agents/urls.py
from django.urls import path
from .views import AgentListView, AgentCreateView, AgentDetailsView, AgentUpdateView, AgentDeleteView

app_name = "agents"
urlpatterns = [
    path("", AgentListView.as_view(), name="agent_list"),
    path("create/", AgentCreateView.as_view(), name="create_agent"),
    path("<int:pk>/details/", AgentDetailsView.as_view(), name="agent_details"),
    path("<int:pk>/update/", AgentUpdateView.as_view(), name="update_agent"),
    path("<int:pk>/delete/", AgentDeleteView.as_view(), name="delete_agent"),

]

djcrm/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include, reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView,PasswordResetDoneView,PasswordResetConfirmView, PasswordResetCompleteView
from leads.views import LeadListView, LeadDetailsView, LeadCreateView, LeadUpdateView, LeadDeleteView, SignupView, landing_page


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', landing_page, name="landing_page"),
    path('leads/', LeadListView.as_view(), name="lead_list"),
    path('leads/create/', LeadCreateView.as_view(), name="create_lead"),
    path('leads/<int:pk>/', LeadDetailsView.as_view(), name="lead_details"),
    path('leads/<int:pk>/update/', LeadUpdateView.as_view(), name="lead_update"),
    path('leads/<int:pk>/delete/', LeadDeleteView.as_view(), name='delete_lead'),
    # TODO Auth urls
    path("login/", LoginView.as_view(template_name='login.html'), name="login"),
    path("signup/", SignupView.as_view(), name="signup"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path('agents/', include('agents.urls', namespace='agents')),
    #TODO password reset urls
    path('password-reset/' , PasswordResetView.as_view(template_name="password-reset.html"), name="reset-password"),
    path('password_reset_confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name="password-reset-confirm.html"),
         name="password_reset_confirm"),
    path('password_reset_done/' , PasswordResetDoneView.as_view(template_name="password-reset-done.html"), name="password_reset_done"),
    path('password_reset_complete/', PasswordResetDoneView.as_view(template_name="password_reset_complete.html"),
         name="password_reset_complete"),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

agents/models.py
from django.db import models

# Create your models here.

agents/forms.py
from django import forms

from django.contrib.auth import get_user_model

User = get_user_model()


class AgentModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'email',
            'username',
            'first_name',
            "last_name"
        )

agents/views.py
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from leads.models import Agent
from .forms import AgentModelForm
import random


class AgentListView(LoginRequiredMixin, generic.ListView):
    template_name = "Agents.html"
    queryset = Agent.objects.all()
    context_object_name = "agents"


class AgentCreateView(LoginRequiredMixin, generic.CreateView):
    template_name = "Agents-create.html"
    form_class = AgentModelForm
    success_url = reverse_lazy('agent-list')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_agent = True
        user.is_organiser = False
        user.set_password(f"{random.randint(0, 10000)}")
        user.save()
        Agent.objects.create(
            user=user,
            organisation=self.request.user.userprofile
        )
        return super(AgentCreateView, self).form_valid(form)


class AgentDetailsView(LoginRequiredMixin, generic.DetailView):
    template_name = "agent-details.html"
    queryset = Agent.objects.all()
    context_object_name = 'agent'


class AgentUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Agent
    template_name = "Agent_update.html"
    form_class = AgentModelForm
    success_url = reverse_lazy('agent-list')


class AgentDeleteView(LoginRequiredMixin, generic.DeleteView):
    queryset = Agent.objects.all()
    template_name = 'confirm_delete.html'
    success_url = reverse_lazy('agent_list')

templates/Agent_update.html
{% extends 'base.html'%}
{% load tailwind_filters %}
{% block content %}

<div class=" max-w-lg mx-auto  shadow-md p-3">
    <form method="post" enctype="multipart/form-data" >
      {% csrf_token %}
      {{ form|crispy}}
     <button type="submit" class="btn text-black w-full bg-blue-600 hover:bg-blue-400">update</button>
    </form>
</div>

 {% endblock %}

templates/Agents-create.html
{% extends 'base.html'%}
{% load tailwind_filters %}
{% block content %}

<style>
    input{
        margin: 10px;
        border: solid 1px black;       
    }
    .btn {
        color: black;
    }
</style>         
<div class=" container card" >
    <h1>Create a new  Agent</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
     <button type="submit" class="btn btn-primary">create</button>
    </form>
  
</div>

 {% endblock %}

templates/Agents.html
{% extends "base.html" %}

{% block content %}
<section class="text-gray-700 body-font" style="margin-top:-100px;">
    <div class="container px-5 py-24 mx-auto flex flex-wrap">
        <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
            <div>
                <h4 class="text-4xl text-gray-800">Agents</h4>
                <a class="text-gray-500 hover:text-blue-500" href="#">  
                    View categories
                </a>
            </div>
           
            <div>
                <a class="text-gray-500 hover:text-blue-500" href="/agents/create/">
                    Create a new Agent
                </a>
            </div>
           
        </div>

        <div class="flex flex-col w-full">
            <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                <table class="min-w-full divide-y divide-gray-200">
                    <thead class="bg-gray-50">
                        <tr>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            First Name
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Last Name
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Age
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Email
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Cell Phone Number
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Category
                            </th>
                            <th scope="col" class="relative px-6 py-3">
                            <span class="sr-only">Edit</span>
                            </th>
                            <th scope="col" class="relative px-6 py-3">
                                <span class="sr-only">delete</span>
                                </th>
                        
                        </tr>
                    </thead>
                    <tbody>
                        {% for agent in agents %}
                            <tr class="bg-white">
                                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                    <a class="text-blue-500 hover:text-blue-800" href="/agents/{{agent.pk}}/details">{{ agent.user.username }}</a>
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    {{ agent.user.username }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    {{ agent.user.username }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    {{ agent.user.username }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    {{ agent.user.username }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap">
                                    {% if lead.category %}
                                        <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                                            {{ agent.user.username}}
                                        </span>
                                    {% else %}
                                        <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-gray-100 text-gray-800">
                                            Unassigned
                                        </span>
                                    {% endif %}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                    <a href="/agents/{{agent.pk}}/update" class="text-indigo-600 hover:text-indigo-900">
                                        Edit
                                    </a>
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                    <a href="/agents/{{agent.pk}}/delete" class="text-indigo-600 hover:text-indigo-900">
                                        delete
                                    </a>
                                </td>
                            </tr>

                        {% empty %}

                        <p>There are currently no agents</p>

                        {% endfor %}
                    </tbody>
                </table>
                </div>
            </div>
            </div>
        </div>

        {% if unassigned_leads.exists %}
            <div class="mt-5 flex flex-wrap -m-4">
                <div class="p-4 w-full">
                    <h1 class="text-4xl text-gray-800">Unassigned leads</h1>
                </div>
                {% for lead in unassigned_leads %}
                <div class="p-4 lg:w-1/2 md:w-full">
                    <div class="flex border-2 rounded-lg border-gray-200 p-8 sm:flex-row flex-col">
                        <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
                            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
                                <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                            </svg>
                        </div>
                        <div class="flex-grow">
                            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
                                {{ lead.first_name }} {{ lead.last_name }}
                            </h2>
                            <p class="leading-relaxed text-base">
                                {{ lead.description }}
                            </p>
                            <a href="#" class="mt-3 text-indigo-500 inline-flex items-center">
                                Assign an agent
                                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                                    <path d="M5 12h14M12 5l7 7-7 7"></path>
                                </svg>
                            </a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>
</section>
{% endblock content %}

templates/agent-details.html
{%extends 'base.html'%}

{% block content%}

  {{ agent.user.username }}


{% endblock%}

templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">    
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
  {% include 'navbar.html' %}
{%block content %}
{% endblock %}
</body>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</html>

templates/landing.html
{% extends 'base.html' %}
{% load static %}
{%block content%}
 <section class="text-gray-600 body-font">
  <div class="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
    <div class="lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 flex flex-col md:items-start md:text-left mb-16 md:mb-0 items-center text-center">
      <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900"> Track Your Leads and follow up on Potential Customers
        <br class="hidden lg:inline-block"> with DJangoCRM
      </h1>
      <p class="mb-8 leading-relaxed">Our platform offers you a tool to track and follow up on your leads. You can Assign Agents from the app And track Progress!!
     With us You take a great step to powerful customer relations and glimpse of your business success...
      </p>.

      <div class="flex justify-center">
        <button class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">
          <a href="{%url 'login' %}">login</a>
        </button>
        <button class="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg">
            <a href="{%url 'signup' %}">Sign in</a>
        </button>
      </div>
    </div>
    <div class="lg:max-w-lg lg:w-full md:w-1/2 w-5/6">
      <img  src="{% static 'img/leads.png' %}" class="object-cover object-center rounded" alt="hero" />
    </div>
  </div>
</section>
{% endblock %}

templates/lead_create.html
{% extends 'base.html'%}
{% load tailwind_filters %}
{% block content %}

<div class=" max-w-lg mx-auto  shadow-md p-3">
    <form method="post" enctype="multipart/form-data" >
      {% csrf_token %}
      {{ form|crispy}}
     <button type="submit" class="btn text-black w-full bg-blue-600 hover:bg-blue-400">Create Lead</button>
    </form>
</div>

 {% endblock %}

templates/lead_detail.html
{%extends 'base.html'%}

{% block content%}

<h1>{{lead.first_name}}</h1>

{% endblock%}

templates/lead_update.html
{% extends 'base.html'%}
{% load tailwind_filters %}
{% block content %}

<div class=" max-w-lg mx-auto  shadow-md p-3">
    <form method="post" enctype="multipart/form-data" >
      {% csrf_token %}
      {{ form|crispy}}
     <button type="submit" class="btn text-black w-full bg-blue-600 hover:bg-blue-400">Update Lead</button>
    </form>
</div>

 {% endblock %}

templates/login.html
{% extends 'base.html'%}
{% load tailwind_filters %}
{% block content %}

<div class=" max-w-lg mx-auto  shadow-md p-3 mt-3" >
    <form method="post" enctype="multipart/form-data" >
      {% csrf_token %}
      {{ form|crispy}}
     <button type="submit" class="btn text-black w-full bg-blue-600 hover:bg-blue-400">Log in</button>
    </form>
    <div>
         <a href="{%url 'reset-password' %}">Forgot password?</a>
    </div>
</div>

 {% endblock %}

templates/navbar.html
<nav class="bg-gray-800">
  <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
    <div class="relative flex h-16 items-center justify-between">
      <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
        <!-- Mobile menu button-->
        <button type="button" class="inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white" aria-controls="mobile-menu" aria-expanded="false">
          <span class="sr-only">Open main menu</span>
          <!--
            Icon when menu is closed.

            Heroicon name: outline/bars-3

            Menu open: "hidden", Menu closed: "block"
          -->
          <svg class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>
          <!--
            Icon when menu is open.

            Heroicon name: outline/x-mark

            Menu open: "block", Menu closed: "hidden"
          -->
          <svg class="hidden h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
        <div class="flex flex-shrink-0 items-center">
<!--          <img class="block h-8 w-auto lg:hidden" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=500" alt="Your Company">-->
<!--          <img class="hidden h-8 w-auto lg:block" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=500" alt="Your Company">-->
        </div>
        <div class="hidden sm:ml-6 sm:block">
          <div class="flex space-x-4">
            <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
            <a href="{% url 'landing_page'%}" class="bg-gray-900 text-white px-3 py-2 rounded-md text-sm font-medium" aria-current="page">DjangoCRM</a>

            <a href="{% url 'lead_list' %}" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">Leads</a>

            <a href="{% url 'agents:agent_list' %}" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">Agents</a>

<!--            <a href="#" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">Calendar</a>-->
          </div>
        </div>
      </div>
    <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
    {% if user.is_authenticated %}

         <a href="#" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">{{user.username }}</a>
    {% else %}
        <a href="{% url 'login' %}" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">Login</a>
    {% endif %}
</div>


        <!-- Profile dropdown -->
        <div class="relative ml-3">
          <div>
            <button type="button" class="flex rounded-full bg-gray-800 text-sm focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
              <span class="sr-only">Open user menu</span>
              <img class="h-8 w-8 rounded-full" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSaj0ucKVpTNbey2YUj2f0V_MDQ1G6jBiwt2w&usqp=CAU"alt="">
            </button>
          </div>

<!--          <div class="absolute right-0 z-10 mt-2 w-48 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1">-->
<!--            &lt;!&ndash; Active: "bg-gray-100", Not Active: "" &ndash;&gt;-->
<!--            <a href="#" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-0">Your Profile</a>-->
<!--            <a href="#" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-1">Settings</a>-->
<!--            <a href="#" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-2">Sign out</a>-->
<!--          </div>-->
        </div>
      </div>
    </div>
  </div>

  <!-- Mobile menu, show/hide based on menu state. -->
  <div class="sm:hidden" id="mobile-menu">
    <div class="space-y-1 px-2 pt-2 pb-3">
      <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
      <a href="{% url 'landing_page'%}" class="bg-gray-900 text-white px-3 py-2 rounded-md text-sm font-medium" aria-current="page">DjangoCRM</a>

            <a href="{% url 'lead_list' %}" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">Leads</a>

            <a href="{% url 'agents:agent_list' %}" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">Agents</a>

<!--      <a href="#" class="text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium">Calendar</a>-->
    </div>
  </div>
</nav>

templates/password-reset-confirm.html
{% extends 'base.html'%}


{% block content%}
<form method="post">
    {%csrf_token%}
    {{form.as_p}}
    <button type="submit">Reset password</button>
    <a href="{%url 'login' %}">Back to log in</a>
</form>

{% endblock %}

templates/password_reset_complete.html
Password reset was successful....You can now login

templates/signup.html
{% extends 'base.html'%}
{% load tailwind_filters %}
{% block content %}

<div class=" max-w-lg mx-auto  shadow-md p-3">
    <form method="post" enctype="multipart/form-data" >
      {% csrf_token %}
      {{ form|crispy}}
     <button type="submit" class="btn text-black w-full bg-blue-600 hover:bg-blue-400">Sign in</button>

        <div>
            <p>Already have an Account?</p>
            <a href="{% url 'login'%}">Login</a>
        </div>
    </form>
</div>

 {% endblock %}